travis:
  secure:
    BINSTAR_TOKEN: Qyo24/twx9CjZ2TzWL6ZAcK74jenrSQ055OLmrLEYqPrkBSc4GcP2sknteGGn50/3NuctAkPZ1WPI1eKE84nEGcqtWcpoBkxZeZ3zizwd4Ef+cziPTLqBbHmrAnI8WjtcsDgpUVQtY8HZgZmz//5pJEsPrkhm1bqX7SVYglJ49lgePB4FmfVOchzSxMr/At9ruIuf8B4/gJUrejyrPl/BZgLcMok4SCAgNDHYoECWuXTZZATxXSD8S1yg/hOSTeyF2S69ADQpAwerMiRITpX3yt34eQdqUEr+wQu/2CPN7alvYyXRhYK2nVnBFtqIgo46S8Fl07IWKhTCo3SvIByxQK46PBVa0t/MKoYW/derY9a5j0ay1G+rNjDUWC3pckzUU5rLgI+ck8P3M5oJ/mTUMa+fkK3qRDM83TtA73Nlj5Hlo2k0954BbVRH9UvcidkU97xyz1gnKJOlq/6cHmf4JzIpYUSFLf67B+OgcrgmEwBAbE50OQpRlLDBJVah6HLyPt453+l3uOE55ObdKrsXAcdb6dfXelLsb9FljR08cMAsiL0Eyv090yDO81VkG81SkIM0TFr4RbqJAcDLnq1Rj8EZckC+8jFBy66bkHdCz0bC6kOhXxgq1JyeynXZtjX8P7poC5FmfS1QtB2cySMiSPifraiDEbycS32nowI9Rg=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
