travis:
  secure:
    BINSTAR_TOKEN: lb1E/00nb4yDWsAinqnstlpi43GWsiyZvs5NrGLA9c6/d8W5mWfxpEbmkHhexloswMjlZbmS1lDTz5q2BgyDIaPrfZaxdhioVEf2+S71/H9uYDFWFan+ovX3kCchiwj6QzxD5bDAhLAKDM1rcEJDi3Z8Y1fcgBfp7dYWpInZBYDp7jy2ar1OZ8UfNUTV72ki0OOwZm20I46nUmVGwsJIKAchgeh1/TdP/aPHdXjPYuMy4Gsa+0NVY3lGua524VOX+W2fX55jZssb4jSBS49QMYI+8Mrm5mc65ndb/3EbzGZRzLiTT6NKxbU5nuzy8VK05FCIy9gqJw9VfHB1SxJ/KPq5DBbqUT3QBgXrZU3ARfkje4P3vajdX3p35VyQT0Z32EQF7cmlSixhyG7AU2etyVZ0qNPzPqZia6eI/C1sZqkDD3z5Py2zgBK4Ih88wM11mqg0/W9DXA29B7hlh6ufJxW0hrw8HRSOwNqbr5HKvV/xIm5anNEn1y8fm2T7jUtc30GVwmMOtyaqnvzS3CiTPyyAwOb3ClmQ9sW5TDjj33YUMMRhinRCJFfdz918Eyi6nYFb8Ejla9wSOV7AG5SjLth0bu2FdCKZKaiY9isZQBpzCTjmWuByT78qjYPHLBCmn+QNGN04OiMrOcwXCaXPtL0CD8XFsT9kBJmFfHJyOEg=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
conda_forge_output_validation: true
